### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by Pavel401** [AhmedAbdoElhawary/image_picker_plus#54]
`Because image >=3.2.1 depends on xml ^6.0.1 and image >=3.2.0 <3.2.1 depends on xml ^6.0.0, image >=3.2.0 requires xml ^6.0.0.
And because every version of image_picker_plus depends on image ^3.2.0, every version of image_picker_plus requires xml ^6.0.0.
And because excel 2.0.0-null-safety-3 depends on xml ^5.0.2 and no versions of excel match >2.0.0-null-safety-3 <3.0.0, image_picker_plus is incompatible with excel ^2.0.0-null-safety-3.
So, because myfeats depends on both excel ^2.0.0-null-safety-3 and image_picker_plus ^0.5.5+1, version solving failed.
pub get failed (1; So, because myfeats depends on both excel ^2.0.0-null-safety-3 and image_picker_plus ^0.5.5+1, version solving failed.)
exit code 1
`

I am getting this error after adding the package

**Comment by AhmedAbdoElhawary** [comment]
You can check the last branch #55 

You can add the package from github like:
  image_picker_plus:
    git:
      url: https://github.com/AhmedAbdoElhawary/image_picker_plus
