### ISSUE TITLE
How to select more than 10 image?

### ISSUE THREAD

**Issue by samieruashovo** [AhmedAbdoElhawary/image_picker_plus#57]
Hello, how can I select more than 10 image from gallery?

**Comment by AhmedAbdoElhawary** [comment]
I made a new version (0.5.5+3). You can use maximumSelection(int) in GalleryDisplaySettings.

**Comment by samieruashovo** [comment]
Thank you for the reply :)

**Comment by ali-yousuf** [comment]
Please add this on Readme maximum selection  is 10 And Customize guideline.
