### ISSUE TITLE
Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin.

### ISSUE THREAD

**Issue by IlgamGabdullin** [AhmedAbdoElhawary/image_picker_plus#61]
Hi! I tried to reproduce example normal1 from pub.dev and got error 

`
Failed to build iOS app
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/image_crop-0.4.1/lib/src/crop.dart:63:68: Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin.
crop.dart:63
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
Exited
`

Environment 
`
Flutter version 3.10.0 on channel stable
Dart version 3.0.0
DevTools version 2.23.1
`

**Comment by IlgamGabdullin** [comment]
found same problem in image_crop package [repo](https://github.com/lykhonis/image_crop/issues/105)

**Comment by cenkerkumlucali** [comment]
If you add this code block, you won't encounter the same error.
`image_crop:
    git:
      url: https://github.com/tsafundzic/image_crop.git`

**Comment by GabriellArthur** [comment]
I'm having the same error. I can't use any functionality from the repository, just importing the image_picker_plus already gives an error

**Comment by AhmedAbdoElhawary** [comment]
#67
