### ISSUE TITLE
App Crashes when Camera Opens in MI Note 7s

### ISSUE THREAD

**Issue by flutterflowdevs-prayul** [AhmedAbdoElhawary/image_picker_plus#62]
I am Encountering an issue with Flutter upload image functionality. when I attempt to upload using Mi brand phones, the camera abruptly shuts down and the application restarts. Currently, I am using the Redmi Note 7S, and this problem seems to be specific to Mi phones. On other brands of phones the upload feature works fine. Unfortunately, there are no specific error messages displayed. It showing  loss of device connection in logs. It could possibly be an issue with the Flutter plugin. I am using "image_picker_plus: ^0.5.6+2".

**Comment by AhmedAbdoElhawary** [comment]
try to use #65 and check updates
