### ISSUE TITLE
Suggestion for the Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin.

### ISSUE THREAD

**Issue by GabriellArthur** [AhmedAbdoElhawary/image_picker_plus#63]
The switch from crop to the image_cropper library, which is more current and has more updates and allows users to use your library

About this: 
https://pub.dev/packages/image_cropper

**Comment by hortigado** [comment]
i have the same error

**Comment by hushmand** [comment]
same issue

**Comment by AhmedAbdoElhawary** [comment]
make sure you are in the latest branch #67
