### ISSUE TITLE
Even though my permissions are granted, the photos are still not showing

### ISSUE THREAD

**Issue by cenkerkumlucali** [AhmedAbdoElhawary/image_picker_plus#68]
Hello, I can see that my permissions are granted, and I even printed them to the screen using the package's code, but the photos are not loading. They always stay in the shimmer state. NOTE: I used the provided sample code.

**Comment by AMANUELAB** [comment]
update you   targetSdkVersion 33
 and  compileSdkVersion 33

**Comment by cenkerkumlucali** [comment]
okay, i will try dude

**Comment by AhmedAbdoElhawary** [comment]
Add this permission into your AndroidManifest.xml


<manifest>
    ...
    <application
        android:requestLegacyExternalStorage="true"
    ...
</application>
<uses-permission android:name="android.permission.INTERNET"/>

<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE>" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    </manifest>

**Comment by cenkerkumlucali** [comment]
There isn't something here. I don't see anything and I'm using IOS version not Android

**Comment by AhmedAbdoElhawary** [comment]
It's about permissions, read the doc again. Add those <key>NSPhotoLibraryUsageDescription</key>
<string>your usage description here</string>
<key>NSCameraUsageDescription</key>
<string>your usage description here</string>
<key>NSMicrophoneUsageDescription</key>
<string>your usage description here</string>

**Comment by cenkerkumlucali** [comment]
Hey, I'm already using the image_picker package. I've done all of these things already; otherwise, it wouldn't work. But in your package, there's always a shimmer, and it never ends.
