### ISSUE TITLE
0.5.8 import error

### ISSUE THREAD

**Issue by WuShengXi** [AhmedAbdoElhawary/image_picker_plus#71]
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':image_picker_plus' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':photo_manager'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':image_picker_plus' of type org.gradle.api.Project.

**Comment by AhmedAbdoElhawary** [comment]
See the #72 branch and version 0.5.9
